# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/ruby/ for more details
#
version: 2.1

orbs:
  ruby: circleci/ruby@0.2.1

executors:
  default:
    docker:
      - image: circleci/ruby:2.7.0-node

jobs:
  build:
    executor: default
    steps:
      - checkout
      - ruby/load-cache:
          key: url-shortener
      - ruby/install-deps
      - ruby/save-cache:
          key: url-shortener
  test:
    parallelism: 4
    executor: default
    steps:
      - checkout
      - ruby/load-cache:
          key: url-shortener
      - ruby/install-deps
      - ruby/run-tests

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
